# Default values for elibapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource Namespace ".Values.namespace.name" in namespace "": namespaces ".Values.namespace.name" is forbidden: User "aanno" cannot get resource "namespaces" in API group "" in the namespace ".Values.namespace.name"
# helm.go:84: [debug] namespaces ".Values.namespace.name" is forbidden: User "aanno" cannot get resource "namespaces" in API group "" in the namespace ".Values.namespace.name"
# could not get information about the resource Namespace ".Values.namespace.name" in namespace ""

namespace:
  # in sandbox there is only one ns allowed and `oc get namespaces` is forbidden (for devs)
  enabled: false
  name: aanno-dev

volume:
  enabled: true
  name: ocs-pv-claim

elasticsearch:
  enabled: true


replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
