kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: deploy-backend-template
objects:
- kind: Service
  apiVersion: v1
  metadata:
    creationTimestamp: null
    name: e-library-backend-api-service
    labels:
      name: "e-library-backend-api"
    namespace: ${OC_PROJECT}
  spec:
    ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      name: e-library-backend-api
  status:
    loadBalancer: {}
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    name: e-library-backend-api-route
    labels:
      name: "e-library-backend-api"
    namespace: ${OC_PROJECT}
  spec:
    port:
      targetPort: 3000
    to:
      kind: Service
      name: e-library-backend-api-service
      weight: 100
- kind: Pod
  apiVersion: v1
  metadata:
    name: e-library-backend-api
    labels:
      name: "e-library-backend-api"
    namespace: ${OC_PROJECT}
  spec:
    containers:
    - image: karansingh/e-library-backend-api-ks:latest
      name: e-library-backend-api
      env:
        - name: "NODE_ENV"
          value: "prod"
        - name: "ES_HOST"
          value: "elasticsearch"
        - name: "PORT"
          value: "3000"    
      ports:
      - containerPort: 3000
      - containerPort: 9229    
      resources: {}
    dnsPolicy: ClusterFirst
    restartPolicy: Never
  status: {}
parameters:
  - name: OC_PROJECT
    displayName: project/namespace name
    description: name of project/namespace
    value: aanno-dev
    required: true
