kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: deploy-frontend-template
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: e-library-frontend
      namespace: ${OC_PROJECT}
    spec:
      ports:
      - port: 80
        protocol: TCP
        targetPort: 8080
      selector:
        run: e-library-frontend
    status:
      loadBalancer: {}
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      annotations:
        openshift.io/host.generated: "true"
      name: frontend
      namespace: ${OC_PROJECT}
    spec:
      port:
        targetPort: 80
      to:
        kind: Service
        name: e-library-frontend
        weight: 100
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        run: e-library-frontend
      name: e-library-frontend
      namespace: ${OC_PROJECT}
    spec:
      replicas: 1
      selector:
        matchLabels:
          run: e-library-frontend
      strategy: {}
      template:
        metadata:
          labels:
            run: e-library-frontend
        spec:
          volumes:
          - name: config-volume
            configMap:
              name: env.js       
          containers:
          # - image: karansingh/e-library-frontend-ks:latest
          - image: docker.io/aanno/e-library-frontend:latest
            name: e-library-frontend      
            ports:
            - containerPort: 8080
            volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/env            
parameters:
  - name: OC_PROJECT
    displayName: project/namespace name
    description: name of project/namespace
    value: aanno-dev
    required: true
